### ISSUE TITLE
Changer le champ icon de la table Collection en Image Field

### ISSUE THREAD

**Issue by axelroy** [HE-Arc/LinkYou#1]

**Comment by Ishydo** [comment]
@axelroy 

Pour info ❤️ 

https://docs.djangoproject.com/fr/1.10/ref/models/fields/#django.db.models.ImageField

Dont le fonctionnement est basé sur https://pillow.readthedocs.io/en/4.0.x/ (pip install Pillow)

ça donnera des fields du genre :
```
img_description = models.ImageField(upload_to='uploads/img/coolimages')
```

😉

**Comment by Ishydo** [comment]
Les modèles sont plus ou moins en version finale pour les fonctionnalités de base.

Reste à voir pour permettre l'ordre des liens:

> _NIH_? https://djangopackages.org/grids/g/model-ordering/
