### ISSUE TITLE
Modification des collections

### ISSUE THREAD

**Issue by LumenH** [HE-Arc/LinkYou#11]
Il faut empêcher les autres utilisateurs de modifier les collections qui ne leur appartiennent pas.
Actuellement, pour empêcher les utilisateurs de faire ceci, les boutons de modification ne sont pas affichés si l'utilisateur ne possède pas la collection.
Cela a fait de la même manière que pour le bouton like. Donc :
```python
if self.object.user_it_belongs == self.request.user : 
    canLike = False 
    canModify = True
```
Il faudrait faire cela de manière bien plus "solide".

**Comment by Ishydo** [comment]
Un petit dispatch dans la vue et c'était bon! :smile: (méthode appelée avant de rentrer dans la view)
```
    def dispatch(self, request, *args, **kwargs):
        collection = self.get_object()
        if collection.user_it_belongs != self.request.user:
            return HttpResponseForbidden("Access forbidden!")
        else:
            return super(CollectionUpdateView, self).dispatch(request, *args, **kwargs)
```
