### ISSUE TITLE
Update / Delete des liens dans une collection

### ISSUE THREAD

**Issue by Ishydo** [HE-Arc/LinkYou#7]
S'inspirer des classes de vues / urls créés pour les _Collections_, ça ira tout seul :wink: 

### Views
```
# views.py
CollectionUpdateView(...):
...
CollectionDeleteView(...):
...
```

DEVIENNENT
```
LinkXXView(...):
...
```
### URLs
```
# urls.py
url(r'^collection/delete/(?P<slug>[\w-]+)-(?P<pk>\w+)', views.CollectionDeleteView.as_view(), name='delete_collection'),
url(r'^collection/edit/(?P<slug>[\w-]+)-(?P<pk>\w+)', views.CollectionUpdateView.as_view(), name='update_collection'),
```
DEVIENNENT
```
T'as compris l'idée
```
:muscle: :muscle: 

(On les déplacera par la suite pour séparer les choses correctement (voir commentaire suivant))

**Le contenu des vues est bien évidemment à adapter depuis celles des _Collection_**

:heart:

**Comment by greut** [comment]
Petite proposition d'amélioration djangoiste :

Ce fichier: https://github.com/HE-Arc/LinkYou/blob/develop/LinkYou/urls.py

Ne fait rien.

Alors que: https://github.com/HE-Arc/LinkYou/blob/develop/linkyouapp/urls.py

En fait trop.

- accounts, login, logout, etc. qui n'ont rien à avoir avec votre applications pourraient remonter dans le `urls.py` de base. 
- collection, link, etc. pourraient être séparés en applications propres, pour autant que ça vous semble sensé.

**Comment by Ishydo** [comment]
C'EST BON CAA! :+1:  :100: / :100:
